.downstream_branch:
  trigger:
    branch: $CI_COMMIT_BRANCH

.downstream_common_config:
  extends: .downstream_branch
  stage: test
  needs: ["dynamic_vars"]
  inherit:
    variables: false
  variables:
    OCI_SKIP_PUSH: "true"
  trigger:
    strategy: depend
  when: manual

trigger-development-ska-pst-common:
  extends: .downstream_common_config
  variables:
    PST_OCI_BUILDTOOLS_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-buildtools
    PST_OCI_BUILDTOOLS_TAG: $PST_OCI_BUILDTOOLS_TAG
  trigger:
    project: ska-telescope/pst/ska-pst-common
  when: manual

trigger-development-ska-pst-smrb:
  extends: .downstream_common_config
  variables:
    PST_OCI_COMMON_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-common
  needs:
    - trigger-development-ska-pst-common
  trigger:
    project: ska-telescope/pst/ska-pst-smrb
  when: manual

trigger-development-ska-pst-recv:
  extends: .downstream_common_config
  variables:
    PST_SMRB_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-smrb
  needs:
    - trigger-development-ska-pst-smrb
  trigger:
    project: ska-telescope/pst/ska-pst-recv
  when: manual

trigger-development-ska-pst-dsp:
  extends: .downstream_common_config
  variables:
    PST_SMRB_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-smrb
  needs:
    - trigger-development-ska-pst-smrb
  trigger:
    project: ska-telescope/pst/ska-pst-dsp
  when: manual

trigger-development-ska-pst-integration:
  extends: .downstream_common_config
  variables:
    PST_SMRB_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-smrb
    PST_RECV_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-recv
    PST_DSP_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-dsp
  needs:
    - trigger-development-ska-pst-recv
    - trigger-development-ska-pst-dsp
  trigger:
    project: ska-telescope/pst/ska-pst-integration
  when: manual