dynamic_vars:
  stage: build
  needs: ["oci-image-build"]
  script:
    - echo "PST_OCI_BUILDTOOLS_TAG=$(grep -m 1 -o '[0-9].*' .release)-dev.c${CI_COMMIT_SHORT_SHA}" > build.env
  artifacts:
    reports:
      dotenv: build.env

# Test OCI
test_dada:
  tags:
    - $K8S_TEST_CLUSTER_TAG
  variables:
    PST_OCI_BUILDTOOLS_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-buildtools
    PST_OCI_BUILDTOOLS_IMAGE: ska-pst-buildtools
    PST_OCI_BUILDTOOLS_TAG: $PST_OCI_BUILDTOOLS_TAG
  stage: test
  needs: ["dynamic_vars"]
  image: "$PST_OCI_BUILDTOOLS_REGISTRY/$PST_OCI_BUILDTOOLS_IMAGE:$PST_OCI_BUILDTOOLS_TAG"
  script:
    - dada_db
    - dada_db -d