# Test OCI
test_dada:
  tags:
    - $K8S_TEST_CLUSTER_TAG
  variables:
    PST_OCI_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-buildtools
    PST_OCI_COMMON_BUILDER: ska-pst-buildtools
    PST_OCI_COMMON_TAG: $PST_OCI_COMMON_TAG
  stage: test
  needs:
    - oci-image-build
    - dynamic_vars
  image: "$PST_OCI_REGISTRY/$PST_OCI_COMMON_BUILDER:$PST_OCI_COMMON_TAG"
  script:
    - dada_db
    - dada_db -d