# Test OCI
test_dada:
  tags:
    - $K8S_TEST_CLUSTER_TAG
  variables:
    PST_OCI_BUILDTOOLS_REGISTRY: registry.gitlab.com/ska-telescope/pst/ska-pst-buildtools
    PST_OCI_BUILDTOOLS_IMAGE: ska-pst-buildtools
    PST_OCI_BUILDTOOLS_TAG: $PST_OCI_BUILDTOOLS_TAG
  stage: test
  needs: ["dynamic_vars"]
  image: "$PST_OCI_BUILDTOOLS_REGISTRY/$PST_OCI_BUILDTOOLS_IMAGE:$PST_OCI_BUILDTOOLS_TAG"
  script:
    - dada_db
    - dada_db -d